// src/config/worlds.config.js
export const WORLDS = [
  {
    id: 0,
    name: 'Tally Town',
    emoji: '📋',
    accent: '#38bdf8',
    range: 'Q1–10',
    description: 'Master tally bundles and frequency tables from survey records!',
    conceptFocus: 'tallies_and_frequency',
    boss: { name: 'Chief Tally Master', emoji: '📋', reward: 'Tally Expert Badge 📋' },
  },
  {
    id: 1,
    name: 'Pictograph Island',
    emoji: '🖼️',
    accent: '#4ade80',
    range: 'Q11–20',
    description: 'Decode picture symbols, multiplier keys, and half symbols!',
    conceptFocus: 'pictographs_and_keys',
    boss: { name: 'Island Cartographer', emoji: '🖼️', reward: 'Key Master Badge 🖼️' },
  },
  {
    id: 2,
    name: 'Bar Graph Bay',
    emoji: '📊',
    accent: '#facc15',
    range: 'Q21–30',
    description: 'Read bar heights, scales, intervals, and identify peak values!',
    conceptFocus: 'single_bar_graphs',
    boss: { name: 'Admiral Bar Graph', emoji: '📊', reward: 'Bar Champion Badge 📊' },
  },
  {
    id: 3,
    name: 'Double Bar Delta',
    emoji: '📶',
    accent: '#fb923c',
    range: 'Q31–40',
    description: 'Compare two categories side-by-side with dual series legends!',
    conceptFocus: 'double_bar_graphs',
    boss: { name: 'Delta Commander', emoji: '📶', reward: 'Comparison Pro Badge 📶' },
  },
  {
    id: 4,
    name: 'Line Graph Lookout',
    emoji: '📈',
    accent: '#f472b6',
    range: 'Q41–50',
    description: 'Track changes over time, identify peaks, drops, and steep trends!',
    conceptFocus: 'line_graphs_trends',
    boss: { name: 'Trend Warden', emoji: '📈', reward: 'Trend Analyst Badge 📈' },
  },
  {
    id: 5,
    name: 'Pie Chart Peak',
    emoji: '🥧',
    accent: '#a78bfa',
    range: 'Q51–60',
    description: 'Calculate slice angles, percentages, and total circle sectors (360°)!',
    conceptFocus: 'pie_charts_angles',
    boss: { name: 'Sovereign of Slices', emoji: '🥧', reward: 'Sector Master Badge 🥧' },
  },
  {
    id: 6,
    name: 'Frequency Forest',
    emoji: '🌲',
    accent: '#34d399',
    range: 'Q61–70',
    description: 'Group continuous data into class intervals and calculate totals!',
    conceptFocus: 'grouped_frequency',
    boss: { name: 'Forest Statistician', emoji: '🌲', reward: 'Forest Ranger Badge 🌲' },
  },
  {
    id: 7,
    name: 'Survey Summit',
    emoji: '🏔️',
    accent: '#60a5fa',
    range: 'Q71–80',
    description: 'Analyze real-world surveys, multi-step totals, and differences!',
    conceptFocus: 'survey_analysis',
    boss: { name: 'Summit Analyst', emoji: '🏔️', reward: 'Summit Champion Badge 🏔️' },
  },
  {
    id: 8,
    name: 'Angle Analytics Lab',
    emoji: '🧭',
    accent: '#e879f9',
    range: 'Q81–90',
    description: 'Solve inverse pie chart problems — converting sector angles to values!',
    conceptFocus: 'inverse_pie_math',
    boss: { name: 'Director Protractor', emoji: '🧭', reward: 'Angle Genius Badge 🧭' },
  },
  {
    id: 9,
    name: 'Data Detective HQ',
    emoji: '🕵️',
    accent: '#ffd700',
    range: 'Q91–100',
    description: 'Solve multi-format data mystery cases combining all chart types!',
    conceptFocus: 'mixed_comprehensive',
    boss: { name: 'Grand Data Detective', emoji: '🕵️', reward: 'Grand Master Badge 🏆' },
  },
];

export const BADGES = [
  { id: 'first_data_point', label: 'Data Pioneer',       icon: '🏅', description: 'Answered your very first question correctly!' },
  { id: 'hot_streak',       label: 'Hot Streak',         icon: '🔥', description: 'Achieved a streak of 5 correct answers!' },
  { id: 'super_streak',     label: 'Data Prodigy',       icon: '⚡', description: 'Achieved a 10-question winning streak!' },
  { id: 'lab_champ',        label: 'Lab Champion',       icon: '🧪', description: 'Completed all 4 interactive simulation stations!' },
  { id: 'district_champ',   label: 'World Star',         icon: '⭐', description: 'Scored 9+ correct in a Practice World!' },
  { id: 'boss_slayer',      label: 'Boss Slayer',        icon: '👑', description: 'Defeated a World Boss in battle!' },
  { id: 'century_scorer',   label: 'Centurion',          icon: '🎯', description: 'Answered 20+ questions in Practice!' },
  { id: 'data_master',      label: 'Grand Data Master',  icon: '🏆', description: 'Completed the full 5-phase Diagrams & Tables Quest!' },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 25,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};
